repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0-1
  hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: end-of-file-fixer
